= Data structures
#include "../build/SegmentTree.h.typ"
#include "../build/LazySegmentTree.h.typ"
#include "../build/MergeSortTree.h.typ"
#include "../build/FenwickPURQ.cpp.typ"
#include "../build/FenwickRUPQ.cpp.typ"
#include "../build/FenwickRURQ.cpp.typ"
#include "../build/Fenwick2d.h.typ"
#include "../build/Fenwick2dAdd.h.typ"
#include "../build/Fenwick2dXor.h.typ"
#include "../build/OrderStatisticTree.h.typ"
#include "../build/CoordinateCompression.h.typ"
#include "../build/HashMap.h.typ"
#include "../build/DSU.h.typ"
#include "../build/DSURollback.h.typ"
#include "../build/SubMatrix.h.typ"
#include "../build/Matrix.h.typ"
#include "../build/LineContainer.h.typ"
#include "../build/Treap.h.typ"
#include "../build/RMQ.h.typ"
#include "../build/MoQueries.h.typ"
#include "../build/MergeSortTree.h.typ"
// #include "../build/Trie.cpp.typ"
#include "../build/BinaryTrie.cpp.typ"
#include "../build/SQRTD.cpp.typ"
#include "../build/MOs.cpp.typ"
