#import "@preview/mitex:0.2.7": mi, mitex
= Number theory

== Modular arithmetic
	#include "../build/ModularArithmetic.h.typ"
	#include "../build/ModInverse.h.typ"
	#include "../build/ModPow.h.typ"
	#include "../build/ModLog.h.typ"
	#include "../build/ModSum.h.typ"
	#include "../build/ModMulLL.h.typ"
	#include "../build/ModSqrt.h.typ"

== Primality
	#include "../build/IsPrime.cpp.typ"
	#include "../build/Sieve.h.typ"
	#include "../build/FastSieve.h.typ"
	#include "../build/LinearSieve.cpp.typ"
	#include "../build/SieveSpf.h.typ"
	#include "../build/SieveDivs.h.typ"
	#include "../build/MillerRabin.h.typ"
	#include "../build/Factor.h.typ"
	#include "../build/PrimeFactorization.cpp.typ"

== Divisibility
	#include "../build/euclid.h.typ"
	#include "../build/CRT.h.typ"
	#include "../build/NumberOfDivisors.h.typ"
	#include "../build/PerfectSquare.h.typ"

	=== Bézout's identity
	For #mi(`a \neq`), #mi(`b \neq 0`), then #mi(`d=gcd(a,b)`) is the smallest positive integer for which there are integer solutions to
	#mitex(`ax+by=d`)
	If #mi(`(x,y)`) is one solution, then all solutions are given by
	#mitex(`\left(x+\frac{kb}{\gcd(a,b)}, y-\frac{ka}{\gcd(a,b)}\right), \quad k\in\mathbb{Z}`)

	#include "../build/phiFunction.h.typ"

== Combinatorics
	#include "../build/Combinatorics.cpp.typ"
	#include "../build/Ncr.h.typ"
	#include "../build/Ncr2.h.typ"
// == Fractions
// #include "../build/ContinuedFractions.h.typ"
// #include "../build/FracBinarySearch.h.typ"

== Pythagorean Triples
 The Pythagorean triples are uniquely generated by
 #mitex(`a=k\cdot (m^{2}-n^{2}),\ \,b=k\cdot (2mn),\ \,c=k\cdot (m^{2}+n^{2}),`)
 with #mi(`m > n > 0`), #mi(`k > 0`), #mi(`m \bot n`), and either #mi(`m`) or #mi(`n`) even.

== Primes
	#mi(`p=962592769`) is such that #mi(`2^{21} \mid p-1`), which may be useful. For hashing
	use 970592641 (31-bit number), 31443539979727 (45-bit), 3006703054056749
	(52-bit). There are 78498 primes less than 1 000 000.

	Primitive roots exist modulo any prime power #mi(`p^a`), except for #mi(`p = 2, a > 2`), and there are #mi(`\phi(\phi(p^a))`) many.
	For #mi(`p = 2, a > 2`), the group #mi(`\mathbb Z_{2^a}^\times`) is instead isomorphic to #mi(`\mathbb Z_2 \times \mathbb Z_{2^{a-2}}`).

== Estimates
	#mi(`\sum_{d|n} d = O(n \log \log n)`).

	The number of divisors of #mi(`n`) is at most around 100 for #mi(`n < 5e4`), 500 for #mi(`n < 1e7`), 2000 for #mi(`n < 1e10`), 200\,000 for #mi(`n < 1e19`).

// == Mobius Function
// #mitex(`% 	\mu(n) = \begin{cases} 0 & n \textrm{ is not square free}\\ 1 & n \textrm{ has even number of prime factors}\\ -1 & n \textrm{ has odd number of prime factors}\\\end{cases}
// `)
// Mobius Inversion:
// #mitex(`g(n) = \sum_{d|n} f(d) \Leftrightarrow f(n) = \sum_{d|n} \mu(d)g(n/d)`)
// Other useful formulas/forms:
// 
// #mi(`\sum_{d | n} \mu(d) = [ n = 1]`) (very useful)
// 
// #mi(`g(n) = \sum_{n|d} f(d) \Leftrightarrow f(n) = \sum_{n|d} \mu(d/n)g(d)`)
// 
// #mi(`g(n) = \sum_{1 \leq m \leq n} f(\left\lfloor\frac{n}{m}\right \rfloor ) \Leftrightarrow f(n) = \sum_{1\leq m\leq n} \mu(m)g(\left\lfloor\frac{n}{m}\right\rfloor)`)
