name: Build LaTeX document

on: [push, pull_request]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: reference_material.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy PDF to repository
        run: |
          cp main.pdf icpc-refrence/refrence.pdf
          cd icpc-refrence
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add main.pdf
          git commit -m "Update PDF"
          git push
