name: Build LaTeX document
on:
  push:
    branches:
      - main


permissions: 
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: reference_material.tex

      - name: Check pdf files
        run: |
          file reference_material.pdf | grep -q ' PDF '
          mkdir public
          cp reference_material.pdf public/

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
