name: Build LaTeX document

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full make

      - name: Build PDF with Makefile
        run: make kactl

      - name: Check PDF file
        run: |
          file kactl.pdf | grep -q ' PDF '
          mkdir public
          cp kactl.pdf public/
          cp test-session.pdf public/

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

